name: Playwright POC

on:
  push:
  workflow_dispatch:

jobs:
  playwright-poc:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: kubeshop/setup-testkube@v1
        with:
          organization: tkcorg_c73cc2305fcef73b
          environment: tkcenv_fc6aee4a02516b59
          token: tkcapi_647ea926fb80823b2924af4aa55781

      - run: |
          testkube run testworkflow playwright-poc -f
