name: Playwright POC

on:
  push:
  workflow_dispatch:

jobs:
  playwright-poc:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: kubeshop/setup-testkube@v1
        with:
          organization: tkcorg_c73cc2305fcef73b
          environment: tkcenv_fc6aee4a02516b59
          token: tkcapi_647ea926fb80823b2924af4aa55781

      # Step to run the Testkube command and capture the output
      - name: Run Testkube test workflow
        id: run-testkube
        run: |
          # Run the testkube command and output the result in JSON format
          output=$(testkube run testworkflow playwright-poc-2 --config environment=test --output json)

          # Use jq to extract 'name' from the JSON output
          name=$(echo "$output" | jq -r '.name')

          # Set the extracted values as outputs for this step
          echo "::set-output name=name::$name"

      # Next step where you use the extracted variables
      - name: Watch until test is completed
        run: |
          testkube watch testworkflowexecution ${{ steps.run-testkube.outputs.name }}
