name: Playwright POC

on:
  workflow_call:
    inputs:
      workflow_name:
        description: 'The Testkube workflow name'
        required: true
        type: string
      environment:
        description: 'The environment to run workflow against (dev, test, staging, performance)'
        required: true
        type: string

jobs:
  playwright-poc:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: kubeshop/setup-testkube@v1
        with:
          organization: tkcorg_c73cc2305fcef73b
          environment: tkcenv_fc6aee4a02516b59
          token: tkcapi_647ea926fb80823b2924af4aa55781

      # Step to run the Testkube command and capture the output
      - name: Run Testkube test workflow
        id: run-testkube
        run: |
          # Run the testkube command and output the result in JSON format
          output=$(testkube run testworkflow ${{ inputs.workflow_name }} --config environment=${{ inputs.environment }} --output json)

          # Print the output for debugging purposes
          echo "Testkube Output: $output"

          # Use jq to extract 'name' from the JSON output
          name=$(echo "$output" | jq -r '.name')

          # Set the extracted values as outputs for this step
          echo "::set-output name=name::$name"

      # Next step where you use the extracted variables
      - name: Watch until test is completed
        run: |
          testkube watch testworkflowexecution ${{ steps.run-testkube.outputs.name }}
