# .github/workflows/trigger-testkube.yml
name: Trigger Testkube Workflow

on:
  workflow_dispatch:
    inputs:
      workflow_name:
        description: 'The Testkube workflow name'
        required: true
      environment:
        description: 'The environment to run workflow against (dev, test, staging, performance)'
        required: true
        default: 'test'

jobs:
  trigger-testkube:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger the reusable workflow
      uses: ./.github/workflows/run-testkube.yml
      with:
        workflow_name: ${{ github.event.inputs.workflow_name }}
        environment: ${{ github.event.inputs.environment }}
